#!/bin/bash
# This script gets run for every Maya.env file found by the postflight script
# The absolute path of the Maya.env file this script is responsible for
# patching is in $1.

# Check if cadnano has already patched Maya.env
if grep CADNANO "$1" 1>/dev/null; then
echo "Skipping patch for $1 since it appears to already be patched."
exit
else
# It has not, so append to the file
echo "Patching $1"
cat >> "$1" <<END_HERE_DOC

### Appended by cadnano2 installer `date` ###

CADNANO_PATH=/Applications/cadnano2.app/Contents/Resources/cadnano2
END_HERE_DOC
fi

# Update or add MAYA_PLUG_IN_PATH
if grep MAYA_PLUG_IN_PATH "$1" 1>/dev/null; then
echo "MAYA_PLUG_IN_PATH already in file. Updating."
sed -i '' -e 's/MAYA_PLUG_IN_PATH[^ ]*$/&:\/Applications\/cadnano2.app\/Contents\/Resources\/cadnano2/' "$1"
else
cat >> "$1" <<EOF
MAYA_PLUG_IN_PATH=/Applications/cadnano2.app/Contents/Resources/cadnano2
EOF
fi
