#!/bin/bash
# This script gets run for every Maya.env file found by the postflight script
# The absolute path of the Maya.env file this script is responsible for
# patching is in $1.
if grep spCadNano "$1" 1>/dev/null; then
echo "Skipping patch for $1 since it appears to already be patched."
else
echo "Patching $1"
cat >> "$1" <<END_HERE_DOC
evalDeferred("autoLoadPlugin(\"\", \"spCadNano.py\", \"spCadNano\")");
END_HERE_DOC
fi
