#!/bin/bash

SUPPORTED_MAYA_VERSIONS="2012"

# Prepare to copy PyQt into mayapy framework
unzip /Applications/cadnano2.app/Contents/Resources/PyQtMacMaya.zip -d /tmp

# Copy PyQt for Maya for each supported version (should just be 2012 for now)
for VERSION in ${SUPPORTED_MAYA_VERSIONS}
do

# Patch Maya.env
MAYA_ENV_FILE="${HOME}/Library/Preferences/Autodesk/maya/${VERSION}-x64/Maya.env"
# ${MYPATH}/patch_maya_env ${MAYA_ENV_FILE}

if grep CADNANO "${MAYA_ENV_FILE}" 1>/dev/null; then
echo "Skipping patch for ${MAYA_ENV_FILE} since it appears to already be patched."
exit
else
# It has not, so append to the file
echo "Patching ${MAYA_ENV_FILE}"
cat >> "${MAYA_ENV_FILE}" <<END_HERE_DOC

### Appended by cadnano2 installer `date` ###

CADNANO_PATH=/Applications/cadnano2.app/Contents/Resources/cadnano2
END_HERE_DOC
fi

# Update or add MAYA_PLUG_IN_PATH
if grep MAYA_PLUG_IN_PATH "${MAYA_ENV_FILE}" 1>/dev/null; then
echo "MAYA_PLUG_IN_PATH already in file. Updating."
sed -i '' -e 's/MAYA_PLUG_IN_PATH[^ ]*$/&:\/Applications\/cadnano2.app\/Contents\/Resources\/cadnano2/' "${MAYA_ENV_FILE}"
else
cat >> "${MAYA_ENV_FILE}" <<EOF
MAYA_PLUG_IN_PATH=/Applications/cadnano2.app/Contents/Resources/cadnano2
EOF
fi

# Patch pluginPrefs.mel to auto-load the plugin
MAYA_PLUGIN_PREFS_FILE="${HOME}/Library/Preferences/Autodesk/maya/2012-x64/prefs/pluginPrefs.mel"

if grep spCadNano "${MAYA_PLUGIN_PREFS_FILE}" 1>/dev/null; then
echo "Skipping patch for ${MAYA_PLUGIN_PREFS_FILE} since it appears to already be patched."
else
echo "Patching ${MAYA_PLUGIN_PREFS_FILE}"
cat >> "${MAYA_PLUGIN_PREFS_FILE}" <<END_HERE_DOC
evalDeferred("autoLoadPlugin(\"\", \"spCadNano.py\", \"spCadNano\")");
END_HERE_DOC
fi

# Copy PyQt for Maya
MAYAPY_DIR=/Applications/Autodesk/maya${VERSION}/Maya.app/Contents/Frameworks/Python.framework/Versions/2.6
if [[ -d "${MAYAPY_DIR}" ]] ; then
    # echo "${MAYAPY_DIR} exists"
    cp -R /tmp/PyQtMacMaya/* $MAYAPY_DIR
    # ln -s /Library/Python/2.6/site-packages/sip $MAYAPY_DIR/lib/python2.6/site-packages/sip
fi
done
