#!/bin/bash

SUPPORTED_MAYA_VERSIONS="2012"

# Copy PyQt for Maya for each supported version (should just be 2012 for now)
for VERSION in ${SUPPORTED_MAYA_VERSIONS}
do

# Patch Maya.env
MAYA_ENV_FILE="${HOME}/Library/Preferences/Autodesk/maya/${VERSION}-x64/Maya.env"
# ${MYPATH}/patch_maya_env ${MAYA_ENV_FILE}

if grep CADNANO "${MAYA_ENV_FILE}" 1>/dev/null; then
echo "Skipping patch for ${MAYA_ENV_FILE} since it appears to already be patched."
else
# It has not, so append to the file
echo "Patching ${MAYA_ENV_FILE}"
cat >> "${MAYA_ENV_FILE}" <<END_HERE_DOC

### Appended by cadnano2 installer `date` ###

CADNANO_PATH=/Applications/cadnano2.app/Contents/Resources/cadnano2
END_HERE_DOC
fi

# Update or add MAYA_PLUG_IN_PATH
if grep MAYA_PLUG_IN_PATH "${MAYA_ENV_FILE}" 1>/dev/null; then
echo "MAYA_PLUG_IN_PATH already in Maya.env..."
    if ! grep MAYA_PLUG_IN_PATH "${MAYA_ENV_FILE}" | grep cadnano2 1>/dev/null; then
        echo "cadnano not in MAYA_PLUG_IN_PATH. updating."
        sed -i '' -e 's/MAYA_PLUG_IN_PATH[^ ]*$/&:\/Applications\/cadnano2.app\/Contents\/Resources\/cadnano2/' "${MAYA_ENV_FILE}"
    else
        echo "cadnano already in MAYA_PLUG_IN_PATH path. Skipping update."
    fi
else
echo "MAYA_PLUG_IN_PATH not found in Maya.env. Updating."
cat >> "${MAYA_ENV_FILE}" <<EOF
MAYA_PLUG_IN_PATH=/Applications/cadnano2.app/Contents/Resources/cadnano2
EOF
fi

# Patch pluginPrefs.mel to auto-load the plugin
MAYA_PLUGIN_PREFS_FILE="${HOME}/Library/Preferences/Autodesk/maya/2012-x64/prefs/pluginPrefs.mel"

if grep spCadNano "${MAYA_PLUGIN_PREFS_FILE}" 1>/dev/null; then
echo "Skipping patch for ${MAYA_PLUGIN_PREFS_FILE} since it appears to already be patched."
else
echo "Patching ${MAYA_PLUGIN_PREFS_FILE}"
cat >> "${MAYA_PLUGIN_PREFS_FILE}" <<END_HERE_DOC
evalDeferred("autoLoadPlugin(\"\", \"spCadNano.py\", \"spCadNano\")");
END_HERE_DOC
fi

# Copy PyQt for Maya
MAYAPY_DIR=/Applications/Autodesk/maya${VERSION}/Maya.app/Contents/Frameworks/Python.framework/Versions
if [[ -d "${MAYAPY_DIR}" ]] ; then
    # echo "${MAYAPY_DIR} exists"
    MAYA_SITEPKGS="$MAYAPY_DIR/2.6/lib/python2.6/site-packages"
    if [[ -d $MAYA_SITEPKGS/PyQt4 ]]; then
        echo "Removing existing PyQt4 for maya at ${MAYA_SITEPKGS}/PyQt4"
        rm -rf "${MAYA_SITEPKGS}/PyQt4"
    fi

    echo "Installing PyQt4 for maya at ${MAYA_SITEPKGS}/PyQt4"
    sudo tar -C ${MAYAPY_DIR} -xf /Applications/cadnano2.app/Contents/Resources/PyQtMacMaya.tar.gz
fi
done
