# The MIT License
#
# Copyright (c) 2011 Wyss Institute at Harvard University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# http://www.opensource.org/licenses/mit-license.php

def testMethod(self):
    # Create part
    partButton = self.mainWindow.topToolBar.widgetForAction(self.mainWindow.actionNewHoneycombPart)
    self.click(partButton)

    # Init refs
    sgi = self.documentController.sliceGraphicsItem
    phg = self.documentController.pathHelixGroup
    ash = self.documentController.pathHelixGroup.activeSliceHandle()

    # Playback user input
    self.mousePress(sgi.getSliceHelixByCoord(2, 8), position=QPoint(7, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(2, 8), position=QPoint(8, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(2, 8), position=QPoint(8, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(2, 9), position=QPoint(11, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(2, 9), position=QPoint(12, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(2, 9), position=QPoint(12, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(3, 9), position=QPoint(21, 4), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(3, 9), position=QPoint(21, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(3, 9), position=QPoint(21, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(3, 8), position=QPoint(24, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(3, 8), position=QPoint(22, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(3, 8), position=QPoint(22, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(3, 7), position=QPoint(18, 9), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(3, 7), position=QPoint(18, 9), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(2, 7), position=QPoint(8, 19), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(2, 7), position=QPoint(8, 19), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(2, 14), position=QPoint(13, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(2, 14), position=QPoint(13, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(2, 15), position=QPoint(7, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(2, 15), position=QPoint(7, 11), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(2, 15), position=QPoint(7, 11), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(3, 15), position=QPoint(11, 4), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(3, 15), position=QPoint(11, 4), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(3, 14), position=QPoint(18, 11), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(3, 14), position=QPoint(16, 11), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(3, 14), position=QPoint(16, 11), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(3, 13), position=QPoint(19, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(3, 13), position=QPoint(19, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(2, 13), position=QPoint(14, 18), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(2, 13), position=QPoint(14, 18), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(5, 7), position=QPoint(20, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(5, 7), position=QPoint(20, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(5, 8), position=QPoint(8, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(5, 8), position=QPoint(9, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(5, 8), position=QPoint(9, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 8), position=QPoint(15, 1), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(6, 8), position=QPoint(16, 1), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 8), position=QPoint(16, 1), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 10), position=QPoint(10, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 10), position=QPoint(10, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 9), position=QPoint(17, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 9), position=QPoint(17, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 11), position=QPoint(14, 9), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(6, 11), position=QPoint(15, 9), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 11), position=QPoint(15, 9), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 12), position=QPoint(17, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(6, 12), position=QPoint(18, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 12), position=QPoint(18, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 13), position=QPoint(13, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 13), position=QPoint(13, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(6, 14), position=QPoint(10, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(6, 14), position=QPoint(10, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(5, 14), position=QPoint(18, 15), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(5, 14), position=QPoint(18, 15), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(sgi.getSliceHelixByCoord(5, 15), position=QPoint(9, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseMove(sgi.getSliceHelixByCoord(5, 15), position=QPoint(11, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mouseRelease(sgi.getSliceHelixByCoord(5, 15), position=QPoint(11, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.slicescene)
    self.mousePress(phg.getPathHelix(0), position=QPoint(411, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(408, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(404, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(401, 17), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(401, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(394, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(387, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(384, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(377, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(373, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(370, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(366, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(363, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(356, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(339, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(318, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(294, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(287, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(280, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(270, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(235, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(190, 7), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(190, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(183, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(177, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(166, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(0), position=QPoint(163, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(0), position=QPoint(163, 10), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(1), position=QPoint(149, 3), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(156, 3), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(163, 3), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(194, 3), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(318, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(439, 44), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(584, 44), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(670, 48), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(726, 58), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(750, 65), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(760, 65), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(767, 65), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(1), position=QPoint(767, 65), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(1), position=QPoint(449, 34), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(453, 34), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(460, 41), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(467, 41), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(518, 51), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(563, 58), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(608, 68), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(625, 75), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(667, 86), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(694, 93), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(1), position=QPoint(708, 96), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(1), position=QPoint(708, 96), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(2), position=QPoint(215, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(215, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(218, 20), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(225, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(249, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(287, 27), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(363, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(415, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(429, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(522, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(584, 27), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(605, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(608, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(2), position=QPoint(608, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(2), position=QPoint(612, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(608, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(605, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(601, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(598, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(563, 27), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(442, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(370, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(332, 34), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(311, 34), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(284, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(2), position=QPoint(280, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(2), position=QPoint(280, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(3), position=QPoint(246, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(249, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(252, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(256, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(263, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(287, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(380, 13), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(460, 6), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(491, 6), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(532, 6), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(629, 16), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(3), position=QPoint(643, 16), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(3), position=QPoint(643, 16), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(4), position=QPoint(239, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(242, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(259, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(263, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(280, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(304, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(346, 33), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(377, 33), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(442, 33), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(508, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(587, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(625, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(4), position=QPoint(629, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(4), position=QPoint(629, 23), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(5), position=QPoint(215, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(218, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(225, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(284, 16), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(370, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(467, 19), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(501, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(591, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(715, 40), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(764, 43), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(764, 47), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(5), position=QPoint(764, 47), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(5), position=QPoint(446, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(449, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(453, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(456, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(463, 30), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(494, 33), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(549, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(563, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(591, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(643, 37), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(719, 54), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(5), position=QPoint(753, 57), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(5), position=QPoint(753, 57), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(6), position=QPoint(197, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(204, 22), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(266, 29), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(363, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(439, 29), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(494, 29), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(608, 33), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(650, 33), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(694, 36), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(6), position=QPoint(722, 40), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(6), position=QPoint(722, 40), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(7), position=QPoint(201, -2), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(204, -2), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(208, 2), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(215, 2), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(218, 2), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(225, 2), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(315, 12), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(463, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(508, 26), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(570, 36), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(629, 36), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(667, 40), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(7), position=QPoint(674, 40), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(7), position=QPoint(674, 40), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(8), position=QPoint(211, 29), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(208, 25), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(211, 25), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(215, 25), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(221, 25), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(287, 25), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(387, 32), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(415, 36), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(456, 36), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(536, 36), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(646, 32), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(8), position=QPoint(660, 32), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(8), position=QPoint(660, 32), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(9), position=QPoint(270, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(277, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(294, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(401, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(511, 5), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(570, 15), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(587, 15), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(9), position=QPoint(601, 18), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(9), position=QPoint(601, 18), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(10), position=QPoint(415, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(411, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(408, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(404, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(398, 8), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(356, 1), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(287, -3), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(259, -3), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(232, -6), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseMove(phg.getPathHelix(10), position=QPoint(177, -6), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(10), position=QPoint(177, -6), modifiers=Qt.NoModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(11), position=QPoint(446, 28), modifiers=Qt.AltModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(11), position=QPoint(446, 28), modifiers=Qt.AltModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(phg.getPathHelix(12), position=QPoint(415, 11), modifiers=Qt.AltModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(phg.getPathHelix(12), position=QPoint(415, 11), modifiers=Qt.AltModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mousePress(ash, position=QPoint(15, 1203), modifiers=Qt.AltModifier|Qt.ShiftModifier, qgraphicsscene=self.mainWindow.pathscene)
    self.mouseRelease(ash, position=QPoint(15, 1203), modifiers=Qt.AltModifier|Qt.ShiftModifier, qgraphicsscene=self.mainWindow.pathscene)

    # Verify model for correctness
    refvh0 = """0 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n0 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh0, repr(self.app.v[0]))
    refvh1 = """1 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n1 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_"""
    self.assertEqual(refvh1, repr(self.app.v[1]))
    refvh2 = """2 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n2 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh2, repr(self.app.v[2]))
    refvh3 = """3 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n3 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh3, repr(self.app.v[3]))
    refvh4 = """4 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n4 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh4, repr(self.app.v[4]))
    refvh5 = """5 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n5 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_"""
    self.assertEqual(refvh5, repr(self.app.v[5]))
    refvh6 = """6 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n6 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh6, repr(self.app.v[6]))
    refvh7 = """7 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n7 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh7, repr(self.app.v[7]))
    refvh8 = """8 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n8 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh8, repr(self.app.v[8]))
    refvh9 = """9 Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n9 Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh9, repr(self.app.v[9]))
    refvh10 = """10Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n10Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh10, repr(self.app.v[10]))
    refvh11 = """11Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n11Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh11, repr(self.app.v[11]))
    refvh12 = """12Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n12Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh12, repr(self.app.v[12]))
    refvh13 = """13Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n13Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh13, repr(self.app.v[13]))
    refvh14 = """14Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n14Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh14, repr(self.app.v[14]))
    refvh15 = """15Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n15Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh15, repr(self.app.v[15]))
    refvh16 = """16Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n16Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh16, repr(self.app.v[16]))
    refvh17 = """17Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n17Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh17, repr(self.app.v[17]))
    refvh18 = """18Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n18Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh18, repr(self.app.v[18]))
    refvh19 = """19Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n19Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh19, repr(self.app.v[19]))
    refvh20 = """20Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n20Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh20, repr(self.app.v[20]))
    refvh21 = """21Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n21Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh21, repr(self.app.v[21]))
    refvh22 = """22Scaffold: _,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,> <,_\n22Staple:   _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_ _,_"""
    self.assertEqual(refvh22, repr(self.app.v[22]))

    self.debugHere()
