# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autostapleconfig.ui'
#
# Created: Tue Jan 24 15:16:52 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(549, 389)
        Dialog.setMinimumSize(QtCore.QSize(549, 389))
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setText(QtGui.QApplication.translate("Dialog", "Choose an auto-staple algorithm:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.algoTab = QtGui.QTabWidget(Dialog)
        self.algoTab.setMinimumSize(QtCore.QSize(504, 338))
        self.algoTab.setObjectName(_fromUtf8("algoTab"))
        self.manualTab = QtGui.QWidget()
        self.manualTab.setObjectName(_fromUtf8("manualTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.manualTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.manualDesc = QtGui.QLabel(self.manualTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualDesc.sizePolicy().hasHeightForWidth())
        self.manualDesc.setSizePolicy(sizePolicy)
        self.manualDesc.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.manualDesc.setText(QtGui.QApplication.translate("Dialog", "Complements all scaffold strands with staples, and installs every available staple crossover. Breaking into properly sized staples must be performed manually.", None, QtGui.QApplication.UnicodeUTF8))
        self.manualDesc.setWordWrap(True)
        self.manualDesc.setObjectName(_fromUtf8("manualDesc"))
        self.verticalLayout_3.addWidget(self.manualDesc)
        self.manualButtonBox = QtGui.QDialogButtonBox(self.manualTab)
        self.manualButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.manualButtonBox.setObjectName(_fromUtf8("manualButtonBox"))
        self.verticalLayout_3.addWidget(self.manualButtonBox)
        self.algoTab.addTab(self.manualTab, _fromUtf8(""))
        self.fixedTab = QtGui.QWidget()
        self.fixedTab.setObjectName(_fromUtf8("fixedTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fixedTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fixedDesc = QtGui.QLabel(self.fixedTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixedDesc.sizePolicy().hasHeightForWidth())
        self.fixedDesc.setSizePolicy(sizePolicy)
        self.fixedDesc.setMaximumSize(QtCore.QSize(16777215, 77))
        self.fixedDesc.setText(QtGui.QApplication.translate("Dialog", "Complements all scaffold in the current part with staples, installs every available crossover to form long proto-staples, and then breaks them into pieces as close to targetLength as possible while not exceeding maxLength or undershooting minLength. minLegLength is the minimum bases away from a crosover that a break can appear.", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedDesc.setWordWrap(True)
        self.fixedDesc.setObjectName(_fromUtf8("fixedDesc"))
        self.verticalLayout_2.addWidget(self.fixedDesc)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.maxLengthLabel = QtGui.QLabel(self.fixedTab)
        self.maxLengthLabel.setText(QtGui.QApplication.translate("Dialog", "maxLength", None, QtGui.QApplication.UnicodeUTF8))
        self.maxLengthLabel.setObjectName(_fromUtf8("maxLengthLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.maxLengthLabel)
        self.maxLengthSpinBox = QtGui.QSpinBox(self.fixedTab)
        self.maxLengthSpinBox.setMaximum(10000)
        self.maxLengthSpinBox.setProperty("value", 60)
        self.maxLengthSpinBox.setObjectName(_fromUtf8("maxLengthSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxLengthSpinBox)
        self.minLengthLabel = QtGui.QLabel(self.fixedTab)
        self.minLengthLabel.setText(QtGui.QApplication.translate("Dialog", "minLength", None, QtGui.QApplication.UnicodeUTF8))
        self.minLengthLabel.setObjectName(_fromUtf8("minLengthLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.minLengthLabel)
        self.minLengthSpinBox = QtGui.QSpinBox(self.fixedTab)
        self.minLengthSpinBox.setMaximum(10000)
        self.minLengthSpinBox.setProperty("value", 30)
        self.minLengthSpinBox.setObjectName(_fromUtf8("minLengthSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.minLengthSpinBox)
        self.targetLengthLabel = QtGui.QLabel(self.fixedTab)
        self.targetLengthLabel.setText(QtGui.QApplication.translate("Dialog", "targetLength", None, QtGui.QApplication.UnicodeUTF8))
        self.targetLengthLabel.setObjectName(_fromUtf8("targetLengthLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.targetLengthLabel)
        self.targetLengthSpinBox = QtGui.QSpinBox(self.fixedTab)
        self.targetLengthSpinBox.setMaximum(10000)
        self.targetLengthSpinBox.setProperty("value", 49)
        self.targetLengthSpinBox.setObjectName(_fromUtf8("targetLengthSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.targetLengthSpinBox)
        self.minLegLengthLabel = QtGui.QLabel(self.fixedTab)
        self.minLegLengthLabel.setText(QtGui.QApplication.translate("Dialog", "minLegLength", None, QtGui.QApplication.UnicodeUTF8))
        self.minLegLengthLabel.setObjectName(_fromUtf8("minLegLengthLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.minLegLengthLabel)
        self.minLegLengthSpinBox = QtGui.QSpinBox(self.fixedTab)
        self.minLegLengthSpinBox.setMaximum(10000)
        self.minLegLengthSpinBox.setProperty("value", 3)
        self.minLegLengthSpinBox.setObjectName(_fromUtf8("minLegLengthSpinBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.minLegLengthSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.fixedButtonBox = QtGui.QDialogButtonBox(self.fixedTab)
        self.fixedButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.fixedButtonBox.setObjectName(_fromUtf8("fixedButtonBox"))
        self.verticalLayout_2.addWidget(self.fixedButtonBox)
        self.algoTab.addTab(self.fixedTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.algoTab)
        self.actionCloseDialog = QtGui.QAction(Dialog)
        self.actionCloseDialog.setText(QtGui.QApplication.translate("Dialog", "closeDialog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseDialog.setShortcut(QtGui.QApplication.translate("Dialog", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseDialog.setObjectName(_fromUtf8("actionCloseDialog"))

        self.retranslateUi(Dialog)
        self.algoTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionCloseDialog, QtCore.SIGNAL(_fromUtf8("triggered()")), Dialog.closeDialog)
        QtCore.QObject.connect(self.fixedButtonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.fixedAlgoChosen)
        QtCore.QObject.connect(self.fixedButtonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.closeDialog)
        QtCore.QObject.connect(self.manualButtonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.manualAlgoChosen)
        QtCore.QObject.connect(self.manualButtonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.closeDialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.algoTab.setTabText(self.algoTab.indexOf(self.manualTab), QtGui.QApplication.translate("Dialog", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.algoTab.setTabText(self.algoTab.indexOf(self.fixedTab), QtGui.QApplication.translate("Dialog", "Fixed", None, QtGui.QApplication.UnicodeUTF8))

