######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 22 14:35:01 2011
######################################################################

TEMPLATE = lib
TARGET = graphicsellipseitem
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += graphicsellipseitem.h
SOURCES += graphicsellipseitem.cpp
