######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 8 16:49:51 2011
######################################################################

TEMPLATE = lib
TARGET = testitem
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testitem.h
SOURCES += testitem.cpp
CONFIG += x86_64